mod as_ref;
mod box_heap;
mod btree;
mod dyn_trait;
mod flatten;
mod from;
mod generics;
mod lifetime;
mod map;
mod misc;
mod reference_counter;
mod serde;
mod stack_heap;
mod str;
mod thread;
mod trait_obect;
mod traits;
fn main() {
    // traits::run();
    // generics::run();
    // lifetime::run();
    // stack_heap::run();
    // box_heap::run();
    // dyn_trait::run();
    // trait_obect::run();
    // serde::run();
    // btree::run();
    // from::run();
    // as_ref::run();
    // map::run();
    // misc::run();
    // thread::run();
    // flatten::run();
    // generics::run();
    // reference_counter::run();
    str::run();
}
